### ISSUE TITLE
Cannot Install: AWS Sagemaker (Amazon Linux)

### ISSUE THREAD

**Issue by oliverbeagley** [bsolomon1124/pycld3#7]
Was trying to install `pycld3` on Sagemaker and due to `pip` not using the `protobuf` libraries installed (though in `yum`) it would not build the wheels and so I instead built the `protobuf` libraries from source using

```bash
curl -L -s -o protobuf-all-3.10.0.tar.gz https://github.com/protocolbuffers/protobuf/releases/download/v3.10.0/protobuf-all-3.10.0.tar.gz
tar -xzf protobuf-all-3.10.0.tar.gz && rm -rf protobuf-all-3.10.0.tar.gz
cd protobuf-3.10.0
./configure && make && sudo make install
```

After that `pip` was able to build the wheel and install `pycld3` but would fail to import, giving error

```
ImportError: /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/cld3.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6google8protobuf8internal14DestroyMessageEPKv
```

Am I missing some steps for install or is something else wrong? Also tried with `protobuf` 3.11.4 but that had the same error

**Comment by bsolomon1124** [comment]
Hi @oliverbeagley : sorry this is giving you trouble.  Two comments here:

I've uploaded some Linux wheels to Test PyPI.  They are 'manylinux' so should work on almost any x86-64 Linux variant and should not require protobuf at all.  Could you be kind enough to try on your end?  Should be as simple as:

```shell
$ pip install --index-url https://test.pypi.org/simple/ pycld3
$ python -c 'import cld3; print(cld3.get_language("影響包含對氣候的變化以及自然資源的枯竭程度"))'
```

(And in the `pip install` output, you should see the `.whl` being downloaded rather than a `tar.gz` source distribution.)

Secondly: regardless of the above, in your installation from above, I'm not certain if it makes a difference, but I use a slightly different set of steps:

```
set -e
yum install -y \
        autoconf \
        automake \
        g++ \
        git \
        glibc-headers \
        gzip \
        libtool \
        make \
        zlib-devel
curl -L -s -o protobuf-all-3.10.0.tar.gz https://github.com/protocolbuffers/protobuf/releases/download/v3.10.0/protobuf-all-3.10.0.tar.gz
tar -xzf protobuf-all-3.10.0.tar.gz && rm -rf protobuf-all-3.10.0.tar.gz
cd protobuf-3.10.0
./autogen.sh
./configure --with-zlib --disable-debug
make
sudo make install
ldconfig --verbose

set +e
```

Notice the addition of `./autogen.sh` in particular, which is mentioned in [this protobuf readme](https://github.com/protocolbuffers/protobuf/tree/master/src).

You can find these commands (roughly the same) in a [Dockerfile](https://github.com/bsolomon1124/pycld3/blob/wheels/docker/Dockerfile.protobuf) that is on a branch I'm working on towards building wheels.

Please let me know how this goes!

**Comment by oliverbeagley** [comment]
Can't confirm for Sagemaker in particular but the wheel works on the amazon linux docker image so I'd assume it works for Sagemaker too, thanks!

As an aside, I tried building `protobuf` from source using your script above then `pycld3` after on another amazon linux image, I had to install `gcc-c++` rather than `g++` for `protobuf` to build, then `python3` (shocker) and `python3-devel` to get `pycld3` to build. It looked like `ldconfig` didn't want to bother doing anything for me so I had to set `export LD_LIBRARY_PATH=/usr/local/lib` for `import cld3` to work (was getting errors about `libprotobuf.so` not being found), after which it all worked fine.

The aside was time somewhat wasted as the wheel worked fine by itself but I wanted to conquer installing it from source after all the time I definitely wasted failing to get it to work before 🙂

**Comment by bsolomon1124** [comment]
@oliverbeagley thanks, most of that make sense to me.  Both g++ and gcc-c++ work for me, but it seems like gcc-c++ works in more places.

I'm not surprised that the Python development headers were needed to install the source distribution.  That is par for the course for extension modules as far as I have always seen.  I'm adding that note to the readme.

With the last issue about the shared library not being found - yes, this is a general pain in the arse and tough to get perfect.  The manylinux wheels _should_ solve that completely because they use [auditwheel](https://github.com/pypa/auditwheel) to bundle the protobuf shared libraries into the wheels themselves.  But if you were installing from an sdist (on Linux i686 arch for instance), pypi would refuse to use the 86-64 wheels and you'd need protobuf installed and in the "right place."  And for MacOS, auditwheel isn't even a thing, so even if the wheel exists, the user still needs libprotobuf or they get a really-hard-to-read error related to `dlopen()`.

Thanks for taking the time to help me out here!

**Comment by bsolomon1124** [comment]
[Wheels](https://pypi.org/project/pycld3/#files) are now uploaded to production PyPI.

```
python -m pip install -U pip pycld3
```

Please let me know if anything here is unresolved and I can re-open.  I also updated the [README](https://github.com/bsolomon1124/pycld3/blob/master/README.md) with tips for some of the more tricky install situations.
